<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [29]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [30]:
#Defining Arrays A, B and C
array_A = np.array([[5,2,3], [6,1,3],[2,4,1]])
print("Array_A: ", array_A)
array_B = array_A[:2,:2]
print("Array_B: ", array_B)
array_C = array_A[1:,1:]
print("Array_C: ", array_C)

Array_A:  [[5 2 3]
 [6 1 3]
 [2 4 1]]
Array_B:  [[5 2]
 [6 1]]
Array_C:  [[1 3]
 [4 1]]


In [31]:
#Define Array D
array_D = np.array([[4,-7,4], [5,6,-1], [-4,2,-5]])
#Determine if AD and DA are equals
AD = array_A * array_D
DA = array_D * array_A
comparasion_AD_DA = AD==DA
print("Array_D: ", array_D)
print("Is AD array equal to DA array? ", comparasion_AD_DA.all())
print("Array AD:", AD)
print("Array DA:", DA)

Array_D:  [[ 4 -7  4]
 [ 5  6 -1]
 [-4  2 -5]]
Is AD array equal to DA array?  True
Array AD: [[ 20 -14  12]
 [ 30   6  -3]
 [ -8   8  -5]]
Array DA: [[ 20 -14  12]
 [ 30   6  -3]
 [ -8   8  -5]]


In [33]:
#Calculate manually the determinant of B, check with numpy to confirm the results
#Manully calculated is -7
print("Determinant of B:", round(det(array_B)))

Determinant of B: -7


In [37]:
#Get the inverse of Matrix D, Check whenever confirm that D * D inv and D inv * D are identity matrices
inv_D = inv(array_D)
D_D_inv = array_D * inv_D
D_inv_D = inv_D * array_D
print("Inverted array D",inv_D)
print("D * D inv:", D_D_inv)
print("D inv * D:", D_inv_D)
#Observation: For the matrix D, It doesn't have Identity. One of the rules to identify if a Matrix has an identity is by looking at the determinant, If It's different to 0, It doesn't have one. 
print("Drterminant of D:", det(array_D))

Inverted array D [[ 0.15642458  0.15083799  0.09497207]
 [-0.16201117  0.02234637 -0.13407821]
 [-0.18994413 -0.11173184 -0.32960894]]
D * D inv: [[ 0.62569832 -1.05586592  0.37988827]
 [-0.81005587  0.13407821  0.13407821]
 [ 0.75977654 -0.22346369  1.64804469]]
D inv * D: [[ 0.62569832 -1.05586592  0.37988827]
 [-0.81005587  0.13407821  0.13407821]
 [ 0.75977654 -0.22346369  1.64804469]]
Drterminant of D: -179.0
